name: Package

on:
  pull_request:
    branches:
    - master

jobs:
  windows:
    name: Windows
    runs-on: windows-2019

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Install nexe
        run: yarn add nexe

      - name: Build
        run: yarn build

      - name: bundle
        run: yarn run nexe --target windows-x86-12.16.3 dist/bin/soundbot.js

      - name: Upload exe
        uses: actions/upload-artifact@v2
        with:
          name: soundbot.exe
          path: soundbot.exe

      - name: Upload node_modules
        uses: actions/upload-artifact@v2
        with:
          name: opus.node
          path: node_modules/@discordjs/opus/**/Release/opus.node
